const SHIFT_STATUS = {
PLANNED: 'planned',
ACTIVE: 'active',
COMPLETED: 'completed',
MISSED: 'missed',
EXCEPTION: 'exception'
};
const SHIFT_STATUS_COLORS = {
[SHIFT_STATUS.PLANNED]: '#6b7280', // Gray
[SHIFT_STATUS.ACTIVE]: '#10b981',  // Green
[SHIFT_STATUS.COMPLETED]: '#059669', // Dark Green
[SHIFT_STATUS.MISSED]: '#ef4444',  // Red
[SHIFT_STATUS.EXCEPTION]: '#f59e0b' // Orange
};
const SHIFT_STATUS_LABELS = {
[SHIFT_STATUS.PLANNED]: 'Planned',
[SHIFT_STATUS.ACTIVE]: 'Active',
[SHIFT_STATUS.COMPLETED]: 'Completed',
[SHIFT_STATUS.MISSED]: 'Missed',
[SHIFT_STATUS.EXCEPTION]: 'Exception'
};
const SHIFT_STATUS_ICONS = {
[SHIFT_STATUS.PLANNED]: '⏰',
[SHIFT_STATUS.ACTIVE]: '✅',
[SHIFT_STATUS.COMPLETED]: '✓',
[SHIFT_STATUS.MISSED]: '❌',
[SHIFT_STATUS.EXCEPTION]: '⚠'
};
module.exports = {
SHIFT_STATUS,
SHIFT_STATUS_COLORS,
SHIFT_STATUS_LABELS,
SHIFT_STATUS_ICONS
};